# Generated by Django 3.1.3 on 2020-11-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photobooth',
            options={'verbose_name': 'Photo Booth'},
        ),
    ]
