# Generated by Django 3.1.3 on 2020-12-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('photo_backend', '0003_first_connexion-api'), ('photo_backend', '0004_auto_20201201_1034')]

    dependencies = [
        ('photo_backend', '0002_photo-sync-api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobooth',
            name='sessionkey',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=255)),
                ('expires', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('photobooth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_backend.photobooth')),
            ],
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('device_code', models.CharField(max_length=255)),
                ('user_code', models.CharField(max_length=255)),
                ('interval', models.IntegerField()),
                ('expires_in', models.IntegerField()),
                ('is_validate', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_ask', models.DateTimeField(auto_now=True)),
                ('photobooth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_backend.photobooth')),
            ],
        ),
    ]
