# Generated by Django 3.1.3 on 2020-11-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('photo_backend', '0003_paillasson'), ('photo_backend', '0004_paillasson_client')]

    dependencies = [
        ('photo_backend', '0002_photo-sync-api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paillasson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('code_connexion', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_backend.client')),
            ],
        ),
    ]
