# Generated by Django 3.1.3 on 2020-11-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0002_auto_20201116_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photobooth',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photo_backend.photobooth'),
            preserve_default=False,
        ),
    ]
