# Generated by Django 3.1.3 on 2020-11-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0003_paillasson'),
    ]

    operations = [
        migrations.AddField(
            model_name='paillasson',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_backend.client'),
        ),
    ]
