# Generated by Django 3.1.3 on 2020-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0003_photo_photobooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='sessionkey',
            field=models.CharField(default='9ebbd0b25760557393a43064a92bae539d962103', max_length=64),
            preserve_default=False,
        ),
    ]
