# Generated by Django 3.1.3 on 2020-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('photo_backend', '0005_auto_20201208_1322'), ('photo_backend', '0006_auto_20201208_1323')]

    dependencies = [
        ('photo_backend', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='lien',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
