# Generated by Django 3.1.3 on 2020-11-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0004_photobooth_sessionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
