# Generated by Django 3.1.3 on 2021-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0005_change_for_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='update',
            field=models.BooleanField(default=True),
        ),
    ]
