# Generated by Django 3.1.3 on 2021-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0006_photobooth_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='maintenance',
            field=models.BooleanField(default=True),
        ),
    ]
