# Generated by Django 3.1.3 on 2020-11-19 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0007_auto_20201116_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_create',
            field=models.DateTimeField(),
        ),
    ]
