# Generated by Django 3.1.3 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0007_photobooth_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobooth',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
