# Generated by Django 3.1.3 on 2021-01-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_backend', '0008_auto_20210112_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pb_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('template', models.JSONField()),
            ],
            options={
                'verbose_name': 'Photo Booth',
            },
        ),
    ]
